---
- name: Login to avi
  uri:
    url: "https://{{ avi_credentials.controller }}/login"
    method: post
    validate_certs: "{{ validate_certs }}"
    body_format: form-urlencoded
    body:
      username: "{{ avi_credentials.username }}"
      password: "{{ avi_credentials.password}}"
  register: login_response 

- name: search and remove network from ipam profile
  ansible.builtin.include_tasks: delete_network_from_avi_ipamdnsprofile.yml

- name: Delete Network
  avi_network:
    name: "avi-mon-{{ namespace_name }}-L7-VIP"
    avi_credentials: "{{ avi_credentials }}"
    state: absent
    cloud_ref: "{{'/api/cloud?name='+ cloud_name }}"
  register: avi_network_delete_result

- name: get cloud config by name
  ansible.builtin.include_tasks: get_cloud_config_by_name.yml

- name: set network facts
  set_fact:
    cloud_config_uuid: "{{ cloud_get_result.uuid }}"

- name: Delete Segment and Tier to Cloud Config
  uri:
    url: "https://{{ avi_credentials.controller }}/api/cloud/{{ cloud_config_uuid }}"
    method: PATCH
    validate_certs: "{{ validate_certs }}"
    headers:
      Content-Type: "application/json"
      Accept: "application/json" 
      X-CSRFToken: "{{ login_response.cookies.csrftoken }}"
      Referer: "https://{{ avi_credentials.controller }}"
      X-Avi-Version: "{{ avi_credentials.api_version }}"
      Cookie: "{{ login_response.cookies_string }}"
    body_format: json
    body: "{{ lookup('template', 'templates/delete_segment_and_tier_to_cloud_config.json.j2')}}"
  register: cloud_result

- name: Display modified cloud result
  debug:
    msg: "{{ cloud_result }}"

#the previous step syncs nsxt components with avi.  If it runs too quickly it will create duplicate avi networks therefore we have a 20 second pause.
- name: Wait 20 seconds for cloud to be configured. 
  ansible.builtin.pause:
    seconds: 20

- name: Display Deleted Network object
  debug:
    msg: "{{ avi_network_delete_result }}"

- name: Delete VRFContext SE MGMT DFGW
  avi_vrfcontext:
    avi_credentials: "{{ avi_credentials }}"
    state: absent
    cloud_ref: "{{'/api/cloud?name='+ cloud_name }}"
    name: "avi-mon-{{ namespace_name }}-T1"
  register: avi_vrfcontext
- name: Display created VRFContext object
  debug:
    msg: "{{ avi_vrfcontext }}"
