- name: Get Session Token
  uri:
    url: "https://{{ vcenter_api_host }}/api/session"
    validate_certs: "{{ validate_certs }}"
    method: POST
    user: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json" 
    status_code:
    - 201
  register: vcenter_login

- name: set auth token
  set_fact:
    auth_token: "{{ vcenter_login.json }}"
