- name: Tanzu Cleanup
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  collections:
    - vmware.alb
  vars_files:
    - ../vars/namespace.yml
    - ../vars/infoblox_connection.yml
    - ../vars/vcenter_connection.yml
    - ../vars/nsxt_connection.yml
    - ../vars/avi_connection.yml
    - ../vars/sendgrid_connection.yml
  vars:
    namespace_mode: remove

  tasks:
  - name: validate request
    ansible.builtin.include_tasks: tasks/validate_request.yml
  - name: check out repo
    ansible.builtin.include_tasks: tasks/checkout_config_repo.yml
  - name: read file
    ansible.builtin.include_vars: "{{ tanzu_repo_checkout_dir }}/tanzu/namespaces/{{ namespace_environment }}/{{ namespace_name }}.yml"
  - name: delete nsxt components
    ansible.builtin.include_tasks: tasks/delete_nsxt_components.yml
  - name: delete avi components
    ansible.builtin.include_tasks: tasks/delete_avi_components.yml
  - name: delete namespace
    ansible.builtin.include_tasks: tasks/manage_namespace.yml
  - name: remove networks
    ansible.builtin.include_tasks: tasks/manage_infoblox.yml
  - name: Send Email
    ansible.builtin.include_tasks: tasks/send_mail.yml
  - name: remove config file from repo
    ansible.builtin.include_tasks: tasks/manage_namespace_config.yml
